webapp/tutorial2/remote_con/urls.py
from django.urls import path

from . import views

app_name = 'remote_con'

urlpatterns = [
    path('remote_con_list/', views.Remote_conListView.as_view(), name='remote_con_list'),
    #path('remote_con_create/', views.Remote_conCreateView.as_view(), name='remote_con_create'),
    path('remote_con_form/', views.Remote_conCreateView.as_view(), name='remote_con_form'),
    path('create_done/', views.create_done, name='create_done'),
    path('update/<int:pk>/', views.Remote_conUpdateView.as_view(), name='remote_con_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/', views.Remote_conDeleteView.as_view(), name='remote_con_delete'),
    path('delete_done/', views.delete_done, name='delete_done')
    ]

webapp/tutorial2/tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('remote_con/', include('remote_con.urls')),
]

webapp/tutorial2/remote_con/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
   class Meta:
       #テーブル名の指定
       db_table ="category"
       verbose_name ="カテゴリ"         #追加
       verbose_name_plural ="カテゴリ"  #追加

   #カラム名の定義
   category_name = models.CharField(max_length=255,blank=False,unique=True)

class Remote_con(models.Model):
   class Meta:
       #テーブル名
       db_table ="remote_con"
       verbose_name ="リモコン"
       verbose_name_plural ="リモコン"

   def __str__(self):
       return self.machine_name

   #カラムの定義
   machine_name = models.CharField(verbose_name="機器の名前", max_length=500)
   vertical_angle = models.IntegerField(verbose_name="縦の角度")
   horizontal_angle = models.IntegerField(verbose_name="横の角度")
   infrared = models.CharField(verbose_name="赤外線の値", max_length=1000)

webapp/tutorial2/remote_con/forms.py
from django import forms
from .models import Remote_con
class Remote_conForm(forms.ModelForm):
   """
   新規データ登録画面用のフォーム定義
   """
   class Meta:
       model = Remote_con
       fields =['machine_name', 'vertical_angle', 'horizontal_angle','infrared']

webapp/tutorial2/remote_con/views.py
from django.shortcuts import render
from . forms import Remote_conForm  #forms.pyからRemote_conFormをインポート
from django.urls import reverse_lazy

# Create your views here.
#ここから下を追加
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import Category, Remote_con

#一覧表示用のDjango標準ビュー(ListView)を承継して一覧表示用のクラスを定義
class Remote_conListView(ListView):
   #利用するモデルを指定
   model = Remote_con
   #データを渡すテンプレートファイルを指定
   template_name = 'remote_con/remote_con_list.html'

   #家計簿テーブルの全データを取得するメソッドを定義
   def queryset(self):
       return Remote_con.objects.all()

class Remote_conCreateView(CreateView):
    #利用するモデルを指定
    model = Remote_con
    #利用するフォームクラス名を指定
    form_class = Remote_conForm
    #登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('remote_con:create_done')

def create_done(request):
   #登録処理が正常終了した場合に呼ばれるテンプレートを指定
   return render(request, 'remote_con/create_done.html')

class Remote_conUpdateView(UpdateView):
   #利用するモデルを指定
   model = Remote_con
   #利用するフォームクラス名を指定
   form_class = Remote_conForm
   #登録処理が正常終了した場合の遷移先を指定
   success_url = reverse_lazy('remote_con:update_done')

def update_done(request):
    #更新処理が正常終了した場合に呼ばれるテンプレートを指定
    return render(request, 'remote_con/update_done.html')

class Remote_conDeleteView(DeleteView):
    #利用するモデルを指定
    model = Remote_con
    #削除処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('remote_con:delete_done')

def delete_done(request):
    return render(request, 'remote_con/delete_done.html')

webapp/tutorial2/remote_con/templates/remote_con/base.html
<!doctype html>
<html>
<head>
 <meta charset="utf-8" />
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 {# Bootstrap4を使う #}
 <!-- linkタグでbootstrapのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
 <!-- linkタグでDataTableのcssファイルを読み込む -->
 <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css"/>
 <!-- タイトルの設定-->
 <title>リモコンアプリ</title>
</head>
<body>
 {% block content %}
  <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->
 {% endblock %}
 <!-- bootstrapのjavascript読み込み-->
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
 <!-- DataTablesのjavascript読み込み-->
 <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
 <script>
    jQuery(function($){
      // デフォルトの設定を変更
      $.extend( $.fn.dataTable.defaults, {
          language: {
              url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
              }
              });
      $("#remote_con_list").DataTable({
          "searching": true,     //検索機能
          "paging":   true,      //ページング機能
          "ordering": true,      //ソート機能
          "lengthChange": true,  //件数切り替え機能

          }).columns.adjust().draw();
          });
 </script>
</body>
</html>

webapp/tutorial2/remote_con/templates/remote_con/create_done.html
{% extends 'remote_con/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'remote_con:remote_con_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">リモコンアプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>リモコンアプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ登録が正常終了しました。</div>
{% endblock content %}

webapp/tutorial2/remote_con/templates/remote_con/delete_done.html
{% extends 'remote_con/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'remote_con:remote_con_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">リモコンアプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>リモコンアプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ削除処理が正常終了しました。</div>
{% endblock content %}

webapp/tutorial2/remote_con/templates/remote_con/remote_con_confirm_delete.html
{% extends 'remote_con/base.html' %}
{% block content %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'remote_con:remote_con_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">リモコンアプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <h3>データ削除</h3></div>
       </div>
       <div class="content-wrapper">
         <div class="container-fluid">
           <p>{{ object }} のデータを削除していいですか?</p>

           <form method="post">
             <a class="btn btn-primary"href="{% url 'remote_con:remote_con_list' %}" role="button">戻る</a>
             <button class="btn btn-danger">削除する</button>
             {% csrf_token %}
           </form>
         </div>
       </div>
   </div>
 </div>
{% endblock %}

webapp/tutorial2/remote_con/templates/remote_con/remote_con_form.html
{% extends 'remote_con/base.html' %}
{% load bootstrap %}
{% block content %}
{% load static %}
 <!-- formタグを設定し、postメソッドを指定 -->
 <form method="post">
   <div class="container">
     <div class="row">
       <div class="col-12">
         <div class="content-wrapper">
           <div class="container-fluid">
             <!-- Breadcrumbs-->
             <ol class="breadcrumb">
               <li class="breadcrumb-item">
                 <a href="{% url 'remote_con:remote_con_list' %}">TOP</a>
               </li>
               <li class="breadcrumb-item active">リモコンアプリ</li>
               <li class="breadcrumb-item active">データ登録</li>
             </ol>

             <div class="card mb-3">
               <div class="card-header">
                 <i class="fa fa-server"></i> <h3>データ登録画面</h3></div>
               <!-- データ入力欄 -->
               <div class="card-body">          {{ form |bootstrap}}
                 <script src="{% static 'sample.js' %}"></script>
                 </div>
       </div>
     </div>
     <div class="row">
       <div class="col-12">
         <!-- データ保存ボタンを設定 -->
         <button class="btn btn-info">保存</button>
       </div>
     </div>
   </div>
   {% csrf_token %}
         <!-- formタグを閉じる -->
 </form>
{% endblock %}

webapp/tutorial2/remote_con/templates/remote_con/remote_con_list.html
<!-- 親テンプレートを読み込む-->
{% extends 'remote_con/base.html' %}
{% block content %}
{% load static %}
 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- パンくずリストの設定-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'remote_con:remote_con_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item">
         <a href="{% url 'remote_con:remote_con_form' %}">データ登録</a>
       </li>
     </ol>
     <!--ページタイトル-->
     <div class="card mb-3">
       <div class="card-header">
         <h3><b>リモコンアプリ</b></h3></div>
       <div class="card-body">
         <!-- テーブル表の定義 -->
         <div class="table-responsive">
         <table id=remote_con_list width="100%" class="table table-striped table-bordered table-hover">
           　<!-- 表の列の定義-->
             <thead>
               <tr>
                 <th class="text-center">機器の名前</th>
                 <th class="text-center">縦の角度</th>
                 <th class="text-center">横の角度</th>
                 <!-- <th class="text-center">赤外線の値</th> -->
                 <th class="text-center">更新・削除</th>
               </tr>
             </thead>
           　<!-- ここまでが表の列の定義-->
           　<!-- 表のデータ部分の表示-->
             <tbody>
               {% for item in object_list %}
                 <tr class="odd gradeX text-center">
                   <td class="text-center" width="100"><!--{{ item.machine_name }}-->
                    <button type="submit" class="btn btn-default btn-block operation-button">{{item.machine_name}}</button>
                    <input type="hidden" class="theta" value="{{ item.vertical_angle }}">
                    <input type="hidden" class="phi" value="{{ item.horizontal_angle }}">
                    <input type="hidden" class="data" value="{{ item.infrared }}">
                   </td>
                   <td class="text-center" width="100">{{ item.vertical_angle }}</td>
                   <td class="text-center" width="140">{{ item.horizontal_angle }}</td>
                   <!-- <td class="text-center" width="140">{{ item.infrared }}</td> -->
                   <td class="text-center" width="140">
                     <a class="btn btn-primary"href="{% url 'remote_con:remote_con_update' item.pk %}" role="button">更新ページ</a>
                     <a class="btn btn-danger" href="{% url 'remote_con:remote_con_delete' item.pk %}" role="button">削除ページ</a>
                   </td>
                 </tr>
             {% endfor %}
             <script src="{% static 'sample2.js' %}"></script>
             </tbody>
           　<!-- ここまでが表のデータ部分の表示-->
           </table>
           <!-- ここまでがテーブル表の定義 -->
       </div>
      </div>
      </div>
   </div>
  </div>
{% endblock content %}

webapp/tutorial2/remote_con/templates/remote_con/update_done.html
{% extends 'remote_con/base.html' %}
{% block content %}

 <div class="content-wrapper">
   <div class="container-fluid">
     <!-- Breadcrumbs-->
     <ol class="breadcrumb">
       <li class="breadcrumb-item">
         <a href="{% url 'remote_con:remote_con_list' %}">TOP</a>
       </li>
       <li class="breadcrumb-item active">リモコンアプリ</li>
     </ol>
     <!-- Example DataTables Card-->
     <div class="card mb-3">
       <div class="card-header">
         <i class="fa fa-server"></i> <b>リモコンアプリ</b></div>
       <div class="card-body">
<div class="alert alert-info" role="alert">データ更新処理が正常終了しました。</div>
{% endblock content %}